// <auto-generated />
namespace Coupons.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class changeRequiredFields : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changeRequiredFields));
        
        string IMigrationMetadata.Id
        {
            get { return "201506250047282_changeRequiredFields"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
